import { hijriToGregorian, HIJRI_MONTHS } from "@/lib/astronomy";

/**
 * Format a Date as a UTC date-only ICS value (YYYYMMDD).
 * Islamic month starts are all-day events so we use DATE (not DATE-TIME).
 */
function toIcsDate(d: Date): string {
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}${m}${day}`;
}

/**
 * Generate an ICS (iCalendar) string containing all-day events for the start
 * of each Hijri month in the given Hijri year (astronomical new-moon reckoning).
 *
 * The file can be imported into Google Calendar, Apple Calendar, Outlook, etc.
 */
export function generateHijriCalendarICS(hijriYear: number): string {
    const now = new Date();
    const dtstamp = now.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";

    const events: string[] = [];

    for (let month = 1; month <= 12; month++) {
        const gregStart = hijriToGregorian(hijriYear, month, 1);
        const monthInfo = HIJRI_MONTHS[month - 1] || HIJRI_MONTHS[0];

        // All-day event: DTSTART is the start date, DTEND is the next day
        const startDate = toIcsDate(gregStart);
        const endDate = toIcsDate(new Date(gregStart.getFullYear(), gregStart.getMonth(), gregStart.getDate() + 1));
        const uid = `hilal-${hijriYear}-${month}@moonsighting.live`;

        events.push(
            [
                "BEGIN:VEVENT",
                `UID:${uid}`,
                `DTSTAMP:${dtstamp}`,
                `DTSTART;VALUE=DATE:${startDate}`,
                `DTEND;VALUE=DATE:${endDate}`,
                `SUMMARY:${monthInfo.en} ${hijriYear} AH begins`,
                `DESCRIPTION:Start of ${monthInfo.en} (${monthInfo.ar}) ${hijriYear} AH — Hijri calendar (astronomical reckoning). Generated by Hilal Vision.`,
                `CATEGORIES:Islamic Calendar`,
                "END:VEVENT",
            ].join("\r\n")
        );
    }

    return [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//Hilal Vision//Islamic Calendar//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        `X-WR-CALNAME:Hijri Calendar ${hijriYear} AH`,
        "X-WR-TIMEZONE:UTC",
        ...events,
        "END:VCALENDAR",
    ].join("\r\n");
}

/** Trigger a browser download of the ICS file. */
export function downloadHijriICS(hijriYear: number): void {
    const ics = generateHijriCalendarICS(hijriYear);
    const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `hijri-calendar-${hijriYear}AH.ics`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
